# Generated by Django 5.1.3 on 2024-11-11 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FRUITS', 'Fruits'), ('VEGETABLES', 'Vegetables'), ('CLOTHES', 'Clothes'), ('TECHNIC', 'Technic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.UUIDField(default=uuid.UUID('d128d654-a571-4e65-9235-c032aacab266'), unique=True),
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ManyToManyField(to='stocks.product'),
        ),
    ]
