# Generated by Django 5.1.3 on 2024-11-11 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.product'),
            preserve_default=False,
        ),
    ]
