# Generated by Django 5.1.3 on 2024-11-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_productstock_product_productstock_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='productstock',
            old_name='warehouse',
            new_name='stock',
        ),
    ]
